version: '3.8'

services:
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    labels:
      - "custom.project=mates-rates-store"
      - "custom.service=postgres"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    labels:
      - "custom.project=mates-rates-cache"
      - "custom.service=redis"
    volumes:
      - redis_data:/data

  # cron:
  #   build:
  #     context: .
  #     dockerfile: docker/dockerfile.cron

volumes:
  postgres_data:
  redis_data: